version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "monthly"

  - package-ecosystem: "github-actions"
    directory: "/" # Location of package manifests
    rebase-strategy: disabled
    schedule:
      interval: "monthly"
    groups:
      all:
        patterns:
        - '*'
